version: "3.9"
services:
  database_sistema:
    image: postgres
    container_name: sistema-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=sistema
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app-sistema
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_sistema
    depends_on:
      - database_sistema



volumes:
  pgdata:
    driver: local
